# Generated by Django 6.0.7 on 2026-07-17 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='friendly_title',
            new_name='citizen_title',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='title',
            new_name='official_title',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
    ]
