# Generated by Django 6.0.7 on 2026-08-06 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_friendly_title_chapter_citizen_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.PositiveSmallIntegerField(help_text='Official article number in the Kenyan Constitution.', unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('official_title', models.CharField(help_text='Official constitutional title.', max_length=255)),
                ('citizen_title', models.CharField(help_text='Friendly learner-facing lesson title.', max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', help_text='Curriculum-defined lesson difficulty.', max_length=10)),
                ('xp_reward', models.PositiveSmallIntegerField(default=25, help_text='XP awarded after completing this lesson.', validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_duration_seconds', models.PositiveSmallIntegerField(help_text='Estimated lesson duration in seconds.', validators=[django.core.validators.MinValueValidator(30)])),
                ('is_active', models.BooleanField(default=False, help_text='Controls whether learners can access this lesson.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(help_text='The constitutional chapter this article belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.chapter')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['article_number'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who originally submitted the case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['case_title'],
            },
        ),
        migrations.CreateModel(
            name='CitizenExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(help_text='Plain-language explanation of the constitutional principle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(help_text='The article this explanation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='citizen_explanation', to='content.article')),
            ],
            options={
                'verbose_name': 'Citizen Explanation',
                'verbose_name_plural': 'Citizen Explanations',
            },
        ),
        migrations.CreateModel(
            name='DecisionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(help_text='The case this decision belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='decision_point', to='content.case')),
            ],
            options={
                'verbose_name': 'Decision Point',
                'verbose_name_plural': 'Decision Points',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='content.decisionpoint')),
            ],
            options={
                'ordering': ['decision_point', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_message', models.TextField(help_text="Coaching message explaining the learner's selected choice.")),
                ('performance_level', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Needs Improvement', 'Needs Improvement')], help_text="Educational evaluation of the learner's reasoning.", max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.OneToOneField(help_text='The choice this feedback explains.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='content.choice')),
                ('citizen_explanation', models.ForeignKey(help_text='Reusable constitutional explanation supporting this feedback.', on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='content.citizenexplanation')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['performance_level'],
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(help_text='observable Learning outcome.', max_length=20)),
                ('cognitive_level', models.CharField(choices=[('Understand', 'Understand'), ('Apply', 'Apply'), ('Analyze', 'Analyze'), ('Evaluate', 'Evaluate'), ('Create', 'Create')], default='Understand', help_text='Expected level of learner thinking for this learning objective.', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=1, help_text='The order in which this learning objective should be displayed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(help_text='The article this learning objective belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='content.article')),
            ],
            options={
                'ordering': ['article', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='OfficialConstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constitution_text', models.TextField(help_text='Official wording of the article from the constitution.')),
                ('source_reference', models.CharField(blank=True, help_text='Reference to the source of the official constitutional text or edition.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(help_text='Official wording of the article from the constitution.', on_delete=django.db.models.deletion.CASCADE, related_name='official_constitution', to='content.article')),
            ],
        ),
        migrations.CreateModel(
            name='SafteyShield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_guidance', models.TextField(help_text='Recommended lawful actions citizens should take.')),
                ('common_mistakes', models.TextField(blank=True, help_text='Common misunderstandings of mistakes to avoid.')),
                ('when_to_seek_help', models.TextField(blank=True, help_text='When to seek legal or professional help.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(help_text='The article this article guide belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='saftey_shield', to='content.article')),
            ],
            options={
                'verbose_name': 'Saftey Shield',
                'verbose_name_plural': 'Saftey Shields',
            },
        ),
        migrations.CreateModel(
            name='ArticleCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField()),
                ('usage_type', models.CharField(choices=[('INTRODUCTION', 'introduction'), ('PRIMARY', 'Primary'), ('SUPPLEMENTARY', 'Supplementary')], default='INTRODUCTION', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_cases', to='content.article')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_cases', to='content.case')),
            ],
            options={
                'ordering': ['article', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('article', 'case'), name='unique_case_per_article'), models.UniqueConstraint(fields=('article', 'display_order'), name='unique_case_order_per_article')],
            },
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('decision_point', 'display_order'), name='unique_choice_order_per_decision'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(fields=('article', 'display_order'), name='unique_learning_objective_order_per_article'),
        ),
    ]
