# Generated by Django 6.0.7 on 2026-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_case_citizenexplanation_decisionpoint_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionpoint',
            name='display_order',
            field=models.PositiveIntegerField(default=1, help_text='The order in which this decision point is displayed within the case.'),
        ),
    ]
