# Generated by Django 6.0.7 on 2026-08-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_decisionpoint_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobjective',
            name='statement',
            field=models.CharField(help_text='observable Learning outcome.', max_length=255),
        ),
    ]
