# Generated by Django 6.0.7 on 2026-08-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_learningobjective_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionpoint',
            name='prompt',
            field=models.TextField(blank=True, help_text='The prompt or question that the learner must respond to.', null=True),
        ),
    ]
