# Generated by Django 6.0.7 on 2026-08-10 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_decisionpoint_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionpoint',
            name='case',
            field=models.ForeignKey(help_text='The case this decision belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='decision_point', to='content.case'),
        ),
    ]
