# Generated by Django 6.0.7 on 2026-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_decisionpoint_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionpoint',
            name='prompt',
            field=models.TextField(help_text='The prompt or question that the learner must respond to.'),
        ),
    ]
