# Generated by Django 6.0.7 on 2026-08-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_decisionpoint_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('part_type', models.CharField(choices=[('explicit', 'Explicit constitutional Part'), ('implicit', 'Implicit Chapter Container')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='content.chapter')),
            ],
            options={
                'ordering': ['chapter', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('chapter', 'display_order'), name='unique_part_order_per_chapter')],
            },
        ),
    ]
