# Generated by Django 6.0.7 on 2026-08-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='friendly_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
