# Generated by Django 6.0.7 on 2026-08-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_part_friendly_title_alter_part_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='chapter',
        ),
        migrations.AddField(
            model_name='article',
            name='part',
            field=models.ForeignKey(blank=True, help_text='The part this article belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.part'),
        ),
    ]
