# Generated by Django 6.0.7 on 2026-08-12 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_article_chapter_article_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates whether this article has been published.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Controls whether learners can currently access this lesson.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='part',
            field=models.ForeignKey(help_text='The part this article belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.part'),
        ),
        migrations.AlterField(
            model_name='articlecase',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assignment', to='content.article'),
        ),
        migrations.AlterField(
            model_name='articlecase',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_assignment', to='content.case'),
        ),
    ]
