# Generated by Django 6.0.7 on 2026-08-20 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_articleprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='citizen_explanation',
        ),
        migrations.AlterField(
            model_name='articleprogress',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_progress', to='content.article'),
        ),
        migrations.AlterField(
            model_name='articleprogress',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')]),
        ),
    ]
