# Generated by Django 6.0.7 on 2026-08-21 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_feedback_citizen_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleprogress',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_progress', to='content.article'),
        ),
    ]
