# Generated by Django 6.1 on 2026-09-02 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_decisionresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='current_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='gems_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='streak_freeze_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='total_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EarnedAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_key', models.CharField(max_length=80)),
                ('achievement_name', models.CharField(max_length=120)),
                ('achievement_description', models.TextField(blank=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='content.learnerprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'constraints': [models.UniqueConstraint(fields=('learner_profile', 'achievement_key'), name='unique_earned_achievement_per_profile')],
            },
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_key', models.CharField(max_length=80)),
                ('badge_name', models.CharField(max_length=120)),
                ('badge_description', models.TextField(blank=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='content.learnerprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'constraints': [models.UniqueConstraint(fields=('learner_profile', 'badge_key'), name='unique_earned_badge_per_profile')],
            },
        ),
        migrations.CreateModel(
            name='LearnerEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ARTICLE_COMPLETED', 'Article Completed'), ('APP_OPENED', 'App Opened'), ('BADGE_EARNED', 'Badge Earned'), ('ACHIEVEMENT_EARNED', 'Achievement Earned'), ('STREAK_FROZEN', 'Streak Frozen')], max_length=40)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('timezone_offset_minutes', models.IntegerField(default=0)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'occurred_at'], name='content_lea_user_id_c12fd5_idx')],
            },
        ),
    ]
